providers:
  moyu:
    api_base: https://www.moyu.info/v1
    api_key_env: MOYU_API_KEY
    description: Moyu OpenAI compatible proxy

  deepseek:
    api_base: https://api.deepseek.com
    api_key_env: DEEPSEEK_API_KEY
    description: DeepSeek official OpenAI-compatible API

  siliconflow:
    api_base: https://api.siliconflow.cn/v1
    api_key_env: SILICONFLOW_API_KEY
    description: SiliconFlow OpenAI compatible API


model_assets:
  glm-5-1:
    type: chat
    provider: moyu
    model: glm-5.1
    name:  GLM-5.1
    request_timeout: 180
    streaming: true
    max_tokens: 4096

  kimi-k2-6:
    type: chat
    provider: moyu
    model: kimi-k2.6
    name:  Kimi K2.6
    request_timeout: 180
    streaming: true
    max_tokens: 4096

  gpt-5-4-mini:
    type: chat
    provider: moyu
    model: gpt-5.4-mini
    name:  GPT-5.4 Mini
    request_timeout: 180
    streaming: true
    max_tokens: 4096

  minimax-m2-7:
    type: chat
    provider: moyu
    model: MiniMax/MiniMax-M2.7
    name:  MiniMax M2.7
    request_timeout: 180
    streaming: true
    max_tokens: 4096

  deepseek-v4-flash:
    type: chat
    provider: siliconflow
    model: deepseek-ai/DeepSeek-V4-Flash
    name:  DeepSeek V4 Flash
    request_timeout: 180
    streaming: true
    max_tokens: 4096

  deepseek-v4-pro:
    type: chat
    provider: siliconflow
    model: deepseek-ai/DeepSeek-V4-Pro
    name:  DeepSeek V4 pro
    request_timeout: 180
    streaming: true
    max_tokens: 4096

  qwen3-6-flash:
    type: chat
    provider: moyu
    model: qwen3.6-flash
    name:  Qwen3.6 Flash
    request_timeout: 180
    streaming: true
    max_tokens: 4096

system_roles:
  planner: deepseek-v4-pro
  analysis: deepseek-v4-flash
  generation: deepseek-v4-pro
  tool: deepseek-v4-flash
