"""Document lifecycle status constants and helpers."""

from __future__ import annotations

DOC_STATUS_DRAFT = "draft"
DOC_STATUS_PENDING_REVIEW = "pending_review"
DOC_STATUS_PUBLISHED = "published"
DOC_STATUS_ARCHIVED = "archived"

EDITABLE_DOCUMENT_STATUSES: tuple[str, ...] = (
    DOC_STATUS_DRAFT,
)
REVIEWABLE_DOCUMENT_STATUSES: tuple[str, ...] = (
    DOC_STATUS_DRAFT,
    DOC_STATUS_PENDING_REVIEW,
    DOC_STATUS_PUBLISHED,
)
VISIBLE_ASK_DOCUMENT_STATUSES: tuple[str, ...] = (DOC_STATUS_PUBLISHED,)
PREVIEW_ASK_DOCUMENT_STATUSES: tuple[str, ...] = (
    DOC_STATUS_DRAFT,
    DOC_STATUS_PENDING_REVIEW,
    DOC_STATUS_PUBLISHED,
)

RETRIEVAL_VERSION_CURRENT = "current"
RETRIEVAL_VERSION_LIVE = "live"
