"""Helpers for indexing job lifecycle state."""

INDEX_JOB_STATUS_QUEUED = "queued"
INDEX_JOB_STATUS_PROCESSING = "processing"
INDEX_JOB_STATUS_COMPLETED = "completed"
INDEX_JOB_STATUS_PARTIAL_FAILED = "partial_failed"
INDEX_JOB_STATUS_FAILED = "failed"

ACTIVE_INDEX_JOB_STATUSES = (
    INDEX_JOB_STATUS_QUEUED,
    INDEX_JOB_STATUS_PROCESSING,
)

INDEX_JOB_DOCUMENT_STATUS_QUEUED = "queued"
INDEX_JOB_DOCUMENT_STATUS_PROCESSING = "processing"
INDEX_JOB_DOCUMENT_STATUS_INDEXED = "indexed"
INDEX_JOB_DOCUMENT_STATUS_FAILED = "failed"

